### ISSUE TITLE
Add an option for which folder to watch

### ISSUE THREAD

**Issue by riasvdv** [BlueBayTravel/laravel-elixir-bless#2]
Could you add an option to define which folder to watch? The whole app folder is a bit of an overkill and a bit useless to have bless run when I change a php file.

**Comment by jbrooksuk** [comment]
This is an Gulp/Elixir issue. This package isn't adding anything to the `watch` task.

**Comment by riasvdv** [comment]
In `.watch('./app/**');` You are specifying which directory to watch. I believe this can be changed, no?

**Comment by jbrooksuk** [comment]
You're completely correct, my mistake!
